### ISSUE TITLE
Define Format for Submissions

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/conf_2014#13]
Before you make the announcement about the call for abstracts and papers, you need to define the requirements for the submission format for the abstracts.

Additionally, it is usually also good to be ready at the same time with information about the format and submission process for the papers that will eventually go in the proceedings.

Last year the abstracts had the following requirements :

"""
The 150-300 word abstract should concisely describe software of interest to the SciPy community, tools or techniques for more effective computing, or how scientific Python was applied to solve a research problem. A traditional background/motivation, methods, results, and conclusion structure is encouraged but not required. Links to project websites, source code repositories, figures, full papers, and evidence of public speaking ability are encouraged.

Each abstract will be peer-reviewed by multiple members of the Program Committee Board. Please submit your abstract at the SciPy 2013 website [2] abstract submission form. Abstracts will be accepted for posters or presentations.
"""

**Comment by jaberg** [comment]
The first paragraph suggests that abstracts themselves (e.g. 150 - 300 words) should have all the sections of a full paper -- is that the intent?

The second paragraph uses "peer-review" in a non-standard way. To me, review by program committee is a non-peer-review approach. Maybe "Abstracts will be reviewed by the Program Committee Board" would be clearer?

Also, @stefanv and I are still not quite ready with the exact protocol for turning abstracts into papers. I think we can say that the authors of accepted abstracts are invited to submit full papers by DATE which will be subject to a peer review process, and published on the conference web page and within the proceedings of SciPy2014. Details of the submission and review process will follow at LINK.

**Comment by katyhuff** [comment]
Yes, they should have the aspects of a full paper. 

We should definitely change peer-review to "will be reviewed by..."

The preliminary protocol description that you describe is fine. Indeed, the last sentence isn't even necessary at this stage. ("Details of the submission and review process will follow at LINK." can wait until we invite folks, if you need more time)

**Comment by katyhuff** [comment]
closing for age. Handled in 2014.
