### ISSUE TITLE
setup symposion site

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/conf_2014#3]

**Comment by polarbeardesign** [comment]
Should we work with what we have from 2013 (changing all the 2013s to 2014s) or better to create a new 2014 'instance'. (I think Eldarion created the 2013 for us last time. Is creating a new one something we can do?)

**Comment by aterrel** [comment]
@mrterry Might have more input, but ultimately whatever works...

**Comment by mrterry** [comment]
So long as we keep the 2013 site up, we should do whatever requires the least amount of (amortized) work.

**Comment by polarbeardesign** [comment]
Just to summarize - Eldarion, the creator of Symposion, set up an instance of Symposion [SciPy2013] for us last year (for a fee). We never got it to production and used PHP/MySQL for 2013. 

I just raised the issue above, not being familiar with Symposion, to see if anyone had an opinion on using what we had from last year (Symposion SciPy2013), and just replace all "2013" with "2014", or try to generate a new Symposion SciPy2014 instance.

I have done the find and replace locally on my copy of Symposion SciPy2013 and it seems to be working so far. So will continue down that path.

The (PHP/MySQL) SciPy2013 site is unaffected by this.

**Comment by mrterry** [comment]
Sounds good. Thanks for the background.

**Comment by codersquid** [comment]
I will experiment with the pycon 2014 repo -- they are using django 1.5.x and newer packages. If I get a handle on that, I could help update ours.

**Comment by aterrel** [comment]
done
