### ISSUE TITLE
Fix conferences.scipy.org

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/conf_2014#4]
The landing page conferences.scipy.org needs to be more than it is.

@pv recommends putting it on scipy.org, 

@aterrel thinks perhaps a place for all the scipy community to blog (such as a simple pelican site).

**Comment by scopatz** [comment]
+1 for a simple pelican site.

**Comment by rgommers** [comment]
What would be the difference with planet.scipy.org?

**Comment by aterrel** [comment]
I was thinking more targeted content with official news and community
maintenance.  A union of efforts rather than a federation.

Right now to get info on the conferences one has to jump all over the place
and wade through a lot of old pages.

**Comment by rgommers** [comment]
Makes sense

**Comment by aterrel** [comment]
I've put up: http://conference.scipy.org/new/

Based on: https://github.com/scipy-conference/conference.scipy.org

Once I get some feedback I'll move it over.

**Comment by scopatz** [comment]
Do you want feedback in this thread or as issues in the scipy-conference/conference.scipy.org repo?

**Comment by aterrel** [comment]
Here might be best.

**Comment by scopatz** [comment]
The news ('/aechives.html') link at the top is broken.  Also the proceedings page is horribly out of date so we shouldn't link to it until it is updates or we our own proceedings page.

**Comment by scopatz** [comment]
The theme looks nice though!

**Comment by aterrel** [comment]
So the proceedings are a different beast.  I haven't touched them.

Will fix the aechives link though.

**Comment by brettrmurphy** [comment]
Page looks good. Would be great to invite someone from EuroSciPy to comment on 2013 on the same page.

**Comment by aterrel** [comment]
@brettrmurphy I mailed their email address.

**Comment by aterrel** [comment]
@scopatz Okay I fixed the proceedings listing.  I'll poke jarrod and stefan about getting the proceedings lists up.

**Comment by scopatz** [comment]
Thanks @aterrel

**Comment by aterrel** [comment]
New code at: https://github.com/scipy-conference/conference.scipy.org
