### ISSUE TITLE
Create Other Conferences Calendar 

### ISSUE THREAD

**Issue by scopatz** [scipy-conference/conf_2014#8]
For communicating where we are all going to.

**Comment by aterrel** [comment]
I created this calendar for playing around...

iCAL: https://www.google.com/calendar/ical/6b3q833ngd26hd8cqg01934dd0%40group.calendar.google.com/public/basic.ics

HTML: https://www.google.com/calendar/embed?src=6b3q833ngd26hd8cqg01934dd0%40group.calendar.google.com&ctz=America/Chicago

**Comment by aterrel** [comment]
@scopatz anything more required here?

**Comment by scopatz** [comment]
I think that the only other thing to do is to give certain people editing priveldges, such as @MatthewTurk and myself.

**Comment by aterrel** [comment]
This should be done.
